server:
  port: 7800
  
spring:
  application:
    name: demo-jpa-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-data-jpa
    username: app_user
    password: app_user
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
